name: Deploy to GKE

on:
  release:
    types: [created]

jobs:
  setup-publish-deploy:
    name: Setup, Publish, Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: mr-pub
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Build Frontend Image
        working-directory: packages/frontend
        run: |-
          docker build . \
            --tag "europe-north1-docker.pkg.dev/mr-pub/default-docker/frontend:$GITHUB_SHA"

      - name: Build Server Image
        working-directory: packages/server
        run: |-
          docker build . \
            --tag "europe-north1-docker.pkg.dev/mr-pub/default-docker/server:$GITHUB_SHA"

      - name: Deploy Images
        run: |-
          docker push "europe-north1-docker.pkg.dev/mr-pub/default-docker/frontend:$GITHUB_SHA"
          docker push \
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/frontend:$GITHUB_SHA" \
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/frontend:$GITHUB_REF"
          docker push \
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/frontend:$GITHUB_SHA"
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/frontend:latest"
          docker push "europe-north1-docker.pkg.dev/mr-pub/default-docker/server:$GITHUB_SHA"
          docker push \
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/server:$GITHUB_SHA" \
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/server:$GITHUB_REF"
          docker push \
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/server:$GITHUB_SHA"
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/server:latest"

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: default-cluster
          location: europe-north1-a
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Rollout Deployment
        working-directory: kubernetes
        run: kubectl rollout restart -f .
