name: Deploy to GKE

on:
  release:
    types: [created]

jobs:
  setup-publish-deploy:
    name: Setup, Publish, Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: mr-pub
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Run Cloud Build
        run: |-
          npm install
          npm run deploy

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: default-cluster
          location: europe-north1-a
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Rollout Deployment
        run: npm run force-update-cluster
