name: Deploy to GKE

on:
  release:
    types: [created]

jobs:
  setup-publish-deploy:
    name: Setup, Publish, Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: mister-pub
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: default-cluster
          location: europe-north1-a
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Build Frontend Image
        working-directory: packages/frontend
        run: |-
          docker build . \
            --tag "europe-north1-docker.pkg.dev/mister-pub/default-docker/frontend:$GITHUB_SHA"
          docker image tag \
            "europe-north1-docker.pkg.dev/mister-pub/default-docker/frontend:$GITHUB_SHA" \
            "europe-north1-docker.pkg.dev/mister-pub/default-docker/frontend:${GITHUB_REF#refs/*/}"
          docker image tag \
            "europe-north1-docker.pkg.dev/mister-pub/default-docker/frontend:$GITHUB_SHA" \
            "europe-north1-docker.pkg.dev/mister-pub/default-docker/frontend:latest"

      - name: Prepare Server Credentials
        working-directory: packages/server
        env:
          GCP_SERVICE_WORKER_KEY: ${{ secrets.GCP_SERVICE_WORKER_KEY }}
        run: |-
          mkdir keys
          echo "$GCP_SERVICE_WORKER_KEY" | base64 -d > keys/service-worker.json

      - name: Build Server Image
        working-directory: packages/server
        run: |-
          docker build . \
            --tag "europe-north1-docker.pkg.dev/mister-pub/default-docker/server:$GITHUB_SHA"
          docker tag \
            "europe-north1-docker.pkg.dev/mister-pub/default-docker/server:$GITHUB_SHA" \
            "europe-north1-docker.pkg.dev/mister-pub/default-docker/server:${GITHUB_REF#refs/*/}"
          docker tag \
            "europe-north1-docker.pkg.dev/mister-pub/default-docker/server:$GITHUB_SHA" \
            "europe-north1-docker.pkg.dev/mister-pub/default-docker/server:latest"

      - name: Deploy Images
        run: |-
          docker push --all-tags "europe-north1-docker.pkg.dev/mister-pub/default-docker/frontend"
          docker push --all-tags "europe-north1-docker.pkg.dev/mister-pub/default-docker/server"

      - name: Rollout Deployment
        working-directory: kubernetes
        run: |-
          kubectl rollout restart deployment/mr-pub-frontend
          kubectl rollout restart deployment/mr-pub-server
