name: Deploy to GKE

on:
  release:
    types: [created]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: mr-pub
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev

      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: default-cluster
          location: europe-north1-a
          credentials: ${{ secrets.GCP_SA_KEY }}

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build Image
        working-directory: packages/frontend
        run: |-
          docker build . \
            --tag "europe-north1-docker.pkg.dev/mr-pub/default-docker/frontend:$GITHUB_SHA"
          docker tag \
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/frontend:$GITHUB_SHA" \
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/frontend:${GITHUB_REF#refs/*/}"
          docker tag \
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/frontend:$GITHUB_SHA" \
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/frontend:latest"

      - name: Push Image
        run: |-
          docker push --all-tags "europe-north1-docker.pkg.dev/mr-pub/default-docker/frontend"

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build Image
        working-directory: packages/server
        run: |-
          docker build . \
            --tag "europe-north1-docker.pkg.dev/mr-pub/default-docker/server:$GITHUB_SHA"
          docker image tag \
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/server:$GITHUB_SHA" \
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/server:${GITHUB_REF#refs/*/}"
          docker image tag \
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/server:$GITHUB_SHA" \
            "europe-north1-docker.pkg.dev/mr-pub/default-docker/server:latest"

      - name: Push Image
        run: |-
          docker push --all-tags "europe-north1-docker.pkg.dev/mr-pub/default-docker/server"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    steps:
      - name: Rollout Deployment
        working-directory: kubernetes
        run: |-
          kubectl rollout restart deployment/mr-pub-frontend
          kubectl rollout restart deployment/mr-pub-server
